<?php
/**
 * Project Modules - reusable content sections for the Project Template.
 *
 * A small library of blended title/text/image blocks (Program Story, Guest
 * Artist, Tickets) that each concert page assembles, reorders and toggles per
 * page. Renders at the_content priority 8, one before project-template.php's
 * filter at 9, so output lands as hero -> page blocks -> modules -> Support.
 *
 * Absorbed into ars-nova-core in 1.9.0 from the standalone plugin
 * ars-nova-project-modules, which is retired. Renderers belong in this plugin
 * for the same reason the CPTs do: the previous agency's 18 Flexible Content
 * layouts still hold data and draw nothing, because their renderers lived in
 * the StageHand theme and died with it.
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

define( 'ANSPM_VERSION', ARS_NOVA_CORE_VERSION );
define( 'ANSPM_DIR', ARS_NOVA_CORE_DIR );

/*
 * Fields are still registered in PHP here. That is a KNOWN INTERIM STATE, not a
 * decision - the field group is to be exported from ACF's own Tools > Export
 * (so the JSON is generated by ACF rather than hand-written) and committed to
 * acf-json/, after which this registration block is deleted and the group
 * becomes editable in the admin like every other group. Field key
 * field_anspm_modules and field name ans_project_modules must survive that move
 * unchanged or every module already saved on a page silently stops resolving.
 */

/* ---------------------------------------------------------------------------
 * Is this page on the Project Template?
 *
 * Prefers ars-nova-core's own helper so there is ONE definition. The fallback
 * exists only so this plugin degrades to "renders nothing" rather than fatals
 * if core is deactivated.
 * ------------------------------------------------------------------------ */
function anspm_is_project_page( $post_id ) {
	if ( function_exists( 'arsnova_is_project_template' ) ) {
		return arsnova_is_project_template( $post_id );
	}
	return 'ans-project-template.php' === get_page_template_slug( $post_id );
}

/* ---------------------------------------------------------------------------
 * Field registration
 * ------------------------------------------------------------------------ */

add_action( 'acf/init', 'anspm_register_fields' );

function anspm_register_fields() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return; // ACF Pro not active — nothing to register, nothing renders.
	}

	$background_field = array(
		'key'           => '',
		'label'         => 'Background',
		'name'          => 'background',
		'type'          => 'select',
		'choices'       => array(
			'cream' => 'Cream (#f5f1e8)',
			'white' => 'White',
			'navy'  => 'Navy (reversed text)',
		),
		'default_value' => 'cream',
		'ui'            => 0,
		'instructions'  => 'Alternate cream and white down the page. Navy is for emphasis — use sparingly.',
	);

	$hidden_field = array(
		'key'           => '',
		'label'         => 'Hide this module',
		'name'          => 'hidden',
		'type'          => 'true_false',
		'ui'            => 1,
		'default_value' => 0,
		'instructions'  => 'Keeps the module and its content, but stops it appearing on the site. Use this while waiting on a bio or a photo.',
	);

	// --- Program Story -----------------------------------------------------
	$story_bg     = $background_field;
	$story_bg['key'] = 'field_anspm_story_background';
	$story_hidden = $hidden_field;
	$story_hidden['key'] = 'field_anspm_story_hidden';

	$program_story = array(
		'key'        => 'layout_anspm_program_story',
		'name'       => 'program_story',
		'label'      => 'Program Story',
		'display'    => 'block',
		'sub_fields' => array(
			$story_hidden,
			array(
				'key'          => 'field_anspm_story_eyebrow',
				'label'        => 'Eyebrow',
				'name'         => 'eyebrow',
				'type'         => 'text',
				'instructions' => 'Small gold caps above the heading — e.g. "The Program".',
			),
			array(
				'key'   => 'field_anspm_story_heading',
				'label' => 'Heading',
				'name'  => 'heading',
				'type'  => 'text',
			),
			array(
				'key'          => 'field_anspm_story_body',
				'label'        => 'Body',
				'name'         => 'body',
				'type'         => 'wysiwyg',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'toolbar'      => 'basic',
				'instructions' => 'Images go in the Image field below, not inline — that is what keeps the layout consistent across pages.',
			),
			array(
				'key'           => 'field_anspm_story_image',
				'label'         => 'Image',
				'name'          => 'image',
				'type'          => 'image',
				'return_format' => 'id',
				'preview_size'  => 'medium',
				'library'       => 'all',
			),
			array(
				'key'               => 'field_anspm_story_image_position',
				'label'             => 'Image position',
				'name'              => 'image_position',
				'type'              => 'select',
				'choices'           => array(
					'above' => 'Above the text',
					'below' => 'Below the text',
					'left'  => 'Left of the text (wraps)',
					'right' => 'Right of the text (wraps)',
					'wide'  => 'Full width of the column',
				),
				'default_value'     => 'below',
				'ui'                => 0,
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_anspm_story_image',
							'operator' => '!=empty',
						),
					),
				),
			),
			array(
				'key'               => 'field_anspm_story_caption',
				'label'             => 'Caption',
				'name'              => 'caption',
				'type'              => 'text',
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_anspm_story_image',
							'operator' => '!=empty',
						),
					),
				),
			),
			$story_bg,
		),
	);

	// --- Guest Artist ------------------------------------------------------
	$artist_bg = $background_field;
	$artist_bg['key'] = 'field_anspm_artist_background';
	$artist_bg['default_value'] = 'white';
	$artist_hidden = $hidden_field;
	$artist_hidden['key'] = 'field_anspm_artist_hidden';

	$guest_artist = array(
		'key'        => 'layout_anspm_guest_artist',
		'name'       => 'guest_artist',
		'label'      => 'Guest Artist',
		'display'    => 'block',
		'sub_fields' => array(
			$artist_hidden,
			array(
				'key'           => 'field_anspm_artist_eyebrow',
				'label'         => 'Eyebrow',
				'name'          => 'eyebrow',
				'type'          => 'text',
				'default_value' => 'Guest Artist',
			),
			array(
				'key'   => 'field_anspm_artist_name',
				'label' => 'Name',
				'name'  => 'name',
				'type'  => 'text',
			),
			array(
				'key'          => 'field_anspm_artist_role',
				'label'        => 'Role / one-line intro',
				'name'         => 'role',
				'type'         => 'text',
				'instructions' => 'e.g. "Guest artist Nicolò Spera joins Ars Nova Singers for all three performances."',
			),
			array(
				'key'           => 'field_anspm_artist_portrait',
				'label'         => 'Portrait',
				'name'          => 'portrait',
				'type'          => 'image',
				'return_format' => 'id',
				'preview_size'  => 'medium',
			),
			array(
				'key'          => 'field_anspm_artist_bio',
				'label'        => 'Biography',
				'name'         => 'bio',
				'type'         => 'wysiwyg',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'toolbar'      => 'basic',
			),
			array(
				'key'           => 'field_anspm_artist_second_image',
				'label'         => 'Second image',
				'name'          => 'second_image',
				'type'          => 'image',
				'return_format' => 'id',
				'preview_size'  => 'medium',
				'instructions'  => 'Optional. Appears full width below the biography.',
			),
			array(
				'key'   => 'field_anspm_artist_link_label',
				'label' => 'Link label',
				'name'  => 'link_label',
				'type'  => 'text',
			),
			array(
				'key'               => 'field_anspm_artist_link_url',
				'label'             => 'Link URL',
				'name'              => 'link_url',
				'type'              => 'url',
				'conditional_logic' => array(
					array(
						array(
							'field'    => 'field_anspm_artist_link_label',
							'operator' => '!=empty',
						),
					),
				),
			),
			$artist_bg,
		),
	);

	// --- Tickets -----------------------------------------------------------
	// Modelled directly on the "Choose your night" band on Rivers & Streams:
	// a full-bleed group at Kadence palette 9, 92px vertical padding, a 780px
	// column, anchor #tickets, containing [ans_event_tickets].
	$tickets_bg = $background_field;
	$tickets_bg['key']           = 'field_anspm_tickets_background';
	$tickets_bg['default_value'] = 'palette9';
	// Kadence's own palette class is offered so this band keeps whatever colour
	// palette 9 currently is, without hard-coding a hex we would then have to
	// keep in step with the theme.
	$tickets_bg['choices'] = array(
		'palette9' => 'Kadence palette 9 (matches the current ticket bands)',
		'cream'    => 'Cream (#f5f1e8)',
		'white'    => 'White',
		'navy'     => 'Navy (reversed text)',
	);
	$tickets_hidden = $hidden_field;
	$tickets_hidden['key'] = 'field_anspm_tickets_hidden';
	$tickets_hidden['instructions'] = 'Hides the whole ticket band. Useful before tickets go on sale.';

	$tickets = array(
		'key'        => 'layout_anspm_tickets',
		'name'       => 'tickets',
		'label'      => 'Tickets',
		'display'    => 'block',
		'sub_fields' => array(
			$tickets_hidden,
			array(
				'key'           => 'field_anspm_tickets_heading',
				'label'         => 'Heading',
				'name'          => 'heading',
				'type'          => 'text',
				'default_value' => 'Choose your night',
				'instructions'  => 'Passed straight to the ticket block. Existing pages use "Choose your night", "Reserve your seat", "Reserve a free seat".',
			),
			array(
				'key'           => 'field_anspm_tickets_anchor',
				'label'         => 'Anchor id',
				'name'          => 'anchor',
				'type'          => 'text',
				'default_value' => 'tickets',
				'instructions'  => 'Leave as "tickets" unless you know why you are changing it — the hero button links to #tickets. Only one module on a page should use it.',
			),
			array(
				'key'          => 'field_anspm_tickets_note',
				'label'        => 'Note below the tickets',
				'name'         => 'note',
				'type'         => 'wysiwyg',
				'media_upload' => 0,
				'tabs'         => 'visual',
				'toolbar'      => 'basic',
				'instructions' => 'Optional. e.g. "This concert is free. Reserving a seat costs you nothing and tells us how many chairs to put out."',
			),
			$tickets_bg,
		),
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_anspm_project_modules',
			'title'                 => 'Project Modules',
			'fields'                => array(
				array(
					'key'          => 'field_anspm_modules',
					'label'        => 'Modules',
					'name'         => 'ans_project_modules',
					'type'         => 'flexible_content',
					'button_label' => 'Add module',
					'instructions' => 'Blended title / text / image sections. Add as many as you like, drag to reorder, and use "Hide this module" to park one until its content is ready. These render below the page blocks and above the Support band.',
					'layouts'      => array(
						'layout_anspm_program_story' => $program_story,
						'layout_anspm_guest_artist'  => $guest_artist,
						'layout_anspm_tickets'       => $tickets,
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'page_template',
						'operator' => '==',
						'value'    => 'ans-project-template.php',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'active'                => true,
			'show_in_rest'          => true,
			'description'           => 'Registered in PHP by ars-nova-project-modules. Not editable in admin by design.',
		)
	);
}

/* ---------------------------------------------------------------------------
 * Rendering
 * ------------------------------------------------------------------------ */

/**
 * Map the background choice to a class.
 *
 * 'palette9' is special: it defers to Kadence's own global-palette class rather
 * than a hex of ours, so the ticket band keeps whatever colour palette 9 is set
 * to and follows it if the palette changes. `has-background` is required
 * alongside it or Kadence's rule does not apply.
 */
function anspm_bg_class( $bg ) {
	if ( 'palette9' === $bg ) {
		return 'anspm-band--palette9 has-theme-palette-9-background-color has-background';
	}
	$allowed = array( 'cream', 'white', 'navy' );
	$bg      = in_array( $bg, $allowed, true ) ? $bg : 'cream';
	return 'anspm-band--' . $bg;
}

/** Shared band open/close so every module is structurally identical. */
function anspm_band_open( $bg, $extra_class = '' ) {
	return '<section class="anspm-band ' . esc_attr( anspm_bg_class( $bg ) )
		. ( $extra_class ? ' ' . esc_attr( $extra_class ) : '' )
		. '"><div class="anspm-band__inner">';
}

function anspm_band_close() {
	return '</div></section>';
}

/** Figure markup for an attachment id. */
function anspm_figure( $image_id, $caption = '', $class = '' ) {
	if ( ! $image_id ) { return ''; }

	$img = wp_get_attachment_image(
		$image_id,
		'large',
		false,
		array( 'class' => 'anspm-figure__img' )
	);
	if ( ! $img ) { return ''; }

	$out  = '<figure class="anspm-figure' . ( $class ? ' ' . esc_attr( $class ) : '' ) . '">';
	$out .= $img;
	if ( '' !== trim( (string) $caption ) ) {
		$out .= '<figcaption class="anspm-figure__caption">' . esc_html( $caption ) . '</figcaption>';
	}
	$out .= '</figure>';

	return $out;
}

function anspm_render_program_story() {
	if ( get_sub_field( 'hidden' ) ) { return ''; }

	$eyebrow  = (string) get_sub_field( 'eyebrow' );
	$heading  = (string) get_sub_field( 'heading' );
	$body     = (string) get_sub_field( 'body' );
	$image    = (int) get_sub_field( 'image' );
	$position = (string) get_sub_field( 'image_position' );
	$caption  = (string) get_sub_field( 'caption' );
	$bg       = (string) get_sub_field( 'background' );

	$figure = anspm_figure( $image, $caption, 'anspm-figure--' . ( $position ? $position : 'below' ) );

	$out = anspm_band_open( $bg, 'anspm-story' );

	if ( '' !== trim( $eyebrow ) ) {
		$out .= '<p class="anspm-eyebrow">' . esc_html( $eyebrow ) . '</p>';
	}
	if ( '' !== trim( $heading ) ) {
		$out .= '<h2 class="anspm-heading">' . wp_kses_post( $heading ) . '</h2>';
	}

	if ( 'above' === $position ) { $out .= $figure; }

	$out .= '<div class="anspm-body">';
	// Float positions must sit INSIDE the text flow or there is nothing to wrap.
	if ( 'left' === $position || 'right' === $position ) { $out .= $figure; }
	$out .= wp_kses_post( $body );
	$out .= '</div>';

	if ( 'below' === $position || 'wide' === $position ) { $out .= $figure; }

	$out .= anspm_band_close();

	return $out;
}

function anspm_render_guest_artist() {
	if ( get_sub_field( 'hidden' ) ) { return ''; }

	$eyebrow  = (string) get_sub_field( 'eyebrow' );
	$name     = (string) get_sub_field( 'name' );
	$role     = (string) get_sub_field( 'role' );
	$portrait = (int) get_sub_field( 'portrait' );
	$bio      = (string) get_sub_field( 'bio' );
	$second   = (int) get_sub_field( 'second_image' );
	$label    = (string) get_sub_field( 'link_label' );
	$url      = (string) get_sub_field( 'link_url' );
	$bg       = (string) get_sub_field( 'background' );

	$out = anspm_band_open( $bg, 'anspm-artist' );

	if ( '' !== trim( $eyebrow ) ) {
		$out .= '<p class="anspm-eyebrow">' . esc_html( $eyebrow ) . '</p>';
	}
	if ( '' !== trim( $name ) ) {
		$out .= '<h2 class="anspm-heading">' . wp_kses_post( $name ) . '</h2>';
	}
	if ( '' !== trim( $role ) ) {
		$out .= '<p class="anspm-artist__role">' . wp_kses_post( $role ) . '</p>';
	}

	$out .= '<div class="anspm-body">';
	$out .= anspm_figure( $portrait, '', 'anspm-figure--portrait' );
	$out .= wp_kses_post( $bio );
	$out .= '</div>';

	$out .= anspm_figure( $second, '', 'anspm-figure--wide' );

	if ( '' !== trim( $label ) && '' !== trim( $url ) ) {
		$out .= '<p class="anspm-actions"><a class="anspm-cta" href="' . esc_url( $url ) . '">'
			. esc_html( $label ) . '</a></p>';
	}

	$out .= anspm_band_close();

	return $out;
}

/**
 * Tickets band.
 *
 * The anchor id matters more than it looks: the Project Template's hero CTA
 * defaults to href="#tickets", so a page whose ticket band has no such id gets
 * a button that goes nowhere. Hence the id lives on the <section> itself and is
 * a field rather than a hard-coded string.
 *
 * do_shortcode() rather than embedding markup — the ticket UI belongs to
 * ars-nova-ticketing-bridge and must stay its responsibility.
 */
function anspm_render_tickets() {
	if ( get_sub_field( 'hidden' ) ) { return ''; }

	$heading = (string) get_sub_field( 'heading' );
	$anchor  = sanitize_title( (string) get_sub_field( 'anchor' ) );
	$note    = (string) get_sub_field( 'note' );
	$bg      = (string) get_sub_field( 'background' );

	if ( '' === $anchor ) { $anchor = 'tickets'; }
	if ( '' === trim( $heading ) ) { $heading = 'Choose your night'; }

	$shortcode = sprintf(
		'[ans_event_tickets heading="%s"]',
		esc_attr( str_replace( '"', '', $heading ) )
	);

	$out  = '<section id="' . esc_attr( $anchor ) . '" class="anspm-band anspm-tickets '
		. esc_attr( anspm_bg_class( $bg ) ) . '"><div class="anspm-band__inner">';
	$out .= do_shortcode( $shortcode );
	if ( '' !== trim( $note ) ) {
		$out .= '<div class="anspm-tickets__note">' . wp_kses_post( $note ) . '</div>';
	}
	$out .= '</div></section>';

	return $out;
}

/**
 * Notice for a layout that has no renderer. Visible to editors only.
 */
function anspm_render_missing( $layout ) {
	if ( ! current_user_can( 'edit_posts' ) ) {
		return '';
	}
	return '<section class="anspm-band anspm-band--cream anspm-missing"><div class="anspm-band__inner">'
		. '<p class="anspm-missing__msg"><strong>Module type &ldquo;'
		. esc_html( $layout )
		. '&rdquo; has no renderer yet.</strong> Its content is saved but nothing draws it. '
		. 'Only logged-in editors can see this message.</p>'
		. '</div></section>';
}

/**
 * Build every module for a page.
 *
 * @param int $post_id Page ID.
 * @return string
 */
function anspm_render_modules( $post_id ) {
	if ( ! function_exists( 'have_rows' ) ) { return ''; }
	if ( ! have_rows( 'ans_project_modules', $post_id ) ) { return ''; }

	$out = '';

	while ( have_rows( 'ans_project_modules', $post_id ) ) {
		the_row();
		switch ( get_row_layout() ) {
			case 'program_story':
				$out .= anspm_render_program_story();
				break;
			case 'guest_artist':
				$out .= anspm_render_guest_artist();
				break;
			case 'tickets':
				$out .= anspm_render_tickets();
				break;
			default:
				// FAIL LOUDLY. A layout with no renderer is exactly how Ligature's 18
				// "Content Blocks" layouts sat dead for years: the data saved perfectly
				// and nothing ever drew it, with no error anywhere. Editors see this;
				// the public never does.
				$out .= anspm_render_missing( (string) get_row_layout() );
				break;
		}
	}

	return $out;
}

/**
 * Append modules to the page content.
 *
 * Priority 8 — deliberately BEFORE ars-nova-core's project template filter at 9,
 * so that filter wraps hero/support around content-plus-modules rather than
 * around content alone. Net order: hero → blocks → modules → support.
 *
 * The three loop guards mirror the Project Template's, and for the same reason:
 * the_content also fires for excerpts, feeds and SEO description generation.
 */
add_filter(
	'the_content',
	function ( $content ) {
		if ( ! is_singular( 'page' ) || ! in_the_loop() || ! is_main_query() ) {
			return $content;
		}

		$post = get_post();
		if ( ! $post || ! anspm_is_project_page( $post->ID ) ) {
			return $content;
		}

		return $content . anspm_render_modules( $post->ID );
	},
	8
);

/* ---------------------------------------------------------------------------
 * REST — read and write a page's modules.
 *
 * WHY THIS EXISTS. Flexible-content rows are not ordinary post meta. ACF stores
 * a serialised layout list in the parent key plus a `_`-prefixed field-key
 * reference beside EVERY sub-value. Writing those by hand through a generic
 * meta tool does not work — wp_set_page_meta silently drops unregistered keys
 * and still answers 200, so the page renders unchanged and nothing reports an
 * error. (Confirmed the hard way on 2026-08-15; same species as the wiki's
 * failure #8.) These routes go through ACF's own update_field(), which is the
 * only supported way to write this shape.
 * ------------------------------------------------------------------------ */

add_action( 'rest_api_init', function () {
	register_rest_route( 'ans-ops/v1', '/project-modules/(?P<id>\d+)', array(
		array(
			'methods'             => 'GET',
			'permission_callback' => function () { return current_user_can( 'edit_pages' ); },
			'callback'            => 'anspm_route_get_modules',
		),
		array(
			'methods'             => 'POST',
			'permission_callback' => function () { return current_user_can( 'edit_pages' ); },
			'callback'            => 'anspm_route_set_modules',
		),
	) );
} );

function anspm_route_get_modules( WP_REST_Request $req ) {
	$id = (int) $req['id'];
	if ( ! get_post( $id ) ) {
		return new WP_Error( 'anspm_no_page', 'No such page.', array( 'status' => 404 ) );
	}
	if ( ! function_exists( 'get_field' ) ) {
		return new WP_Error( 'anspm_no_acf', 'ACF is not active.', array( 'status' => 409 ) );
	}
	$rows = get_field( 'ans_project_modules', $id );

	return array(
		'ok'               => true,
		'page'             => $id,
		'title'            => get_the_title( $id ),
		'project_template' => anspm_is_project_page( $id ),
		'count'            => is_array( $rows ) ? count( $rows ) : 0,
		'modules'          => is_array( $rows ) ? $rows : array(),
		'site'             => home_url(),
		'is_production'    => anspm_is_production(),
	);
}

/** Same production posture as the rest of the Ars Nova plugins. */
function anspm_is_production() {
	if ( function_exists( 'ans_ops_is_production' ) ) {
		return ans_ops_is_production();
	}
	$host = wp_parse_url( home_url(), PHP_URL_HOST );
	return in_array( strtolower( (string) $host ), array( 'arsnovasingers.org', 'www.arsnovasingers.org' ), true );
}

/** Sub-fields we accept per layout. Anything else in the payload is ignored. */
function anspm_allowed_subfields() {
	return array(
		'program_story' => array( 'hidden', 'eyebrow', 'heading', 'body', 'image', 'image_position', 'caption', 'background' ),
		'guest_artist'  => array( 'hidden', 'eyebrow', 'name', 'role', 'portrait', 'bio', 'second_image', 'link_label', 'link_url', 'background' ),
		'tickets'       => array( 'hidden', 'heading', 'anchor', 'note', 'background' ),
	);
}

function anspm_route_set_modules( WP_REST_Request $req ) {
	$id = (int) $req['id'];

	if ( ! get_post( $id ) ) {
		return new WP_Error( 'anspm_no_page', 'No such page.', array( 'status' => 404 ) );
	}
	if ( ! function_exists( 'update_field' ) ) {
		return new WP_Error( 'anspm_no_acf', 'ACF is not active.', array( 'status' => 409 ) );
	}
	if ( anspm_is_production() && ! filter_var( $req->get_param( 'confirm_production' ), FILTER_VALIDATE_BOOLEAN ) ) {
		return new WP_Error( 'anspm_production_blocked', 'This is the production site. Resend with confirm_production=true to proceed.', array( 'status' => 403 ) );
	}

	$modules = $req->get_param( 'modules' );
	if ( ! is_array( $modules ) ) {
		return new WP_Error( 'anspm_bad_payload', 'Provide "modules" as an array of rows, each with acf_fc_layout.', array( 'status' => 400 ) );
	}

	$allowed = anspm_allowed_subfields();
	$rows    = array();
	$skipped = array();

	foreach ( $modules as $i => $module ) {
		if ( ! is_array( $module ) || empty( $module['acf_fc_layout'] ) ) {
			$skipped[] = array( 'index' => $i, 'why' => 'missing acf_fc_layout' );
			continue;
		}
		$layout = (string) $module['acf_fc_layout'];
		if ( ! isset( $allowed[ $layout ] ) ) {
			$skipped[] = array( 'index' => $i, 'why' => 'unknown layout "' . $layout . '"' );
			continue;
		}

		$row = array( 'acf_fc_layout' => $layout );
		foreach ( $allowed[ $layout ] as $sub ) {
			if ( array_key_exists( $sub, $module ) ) {
				$row[ $sub ] = $module[ $sub ];
			}
		}
		$rows[] = $row;
	}

	// Field KEY, not name — update_field() is far more reliable with the key.
	$result = update_field( 'field_anspm_modules', $rows, $id );

	// Verify rather than trust: read it straight back out.
	$readback = function_exists( 'get_field' ) ? get_field( 'ans_project_modules', $id ) : null;
	$written  = is_array( $readback ) ? count( $readback ) : 0;

	if ( count( $rows ) !== $written ) {
		return new WP_REST_Response( array(
			'ok'       => false,
			'error'    => 'Write did not verify: sent ' . count( $rows ) . ' rows, read back ' . $written . '.',
			'result'   => $result,
			'skipped'  => $skipped,
		), 500 );
	}

	return array(
		'ok'            => true,
		'page'          => $id,
		'title'         => get_the_title( $id ),
		'written'       => $written,
		'layouts'       => wp_list_pluck( $rows, 'acf_fc_layout' ),
		'skipped'       => $skipped,
		'site'          => home_url(),
		'is_production' => anspm_is_production(),
	);
}

/**
 * Stylesheet, only on project pages.
 */
add_action(
	'wp_enqueue_scripts',
	function () {
		if ( ! is_singular( 'page' ) || ! anspm_is_project_page( get_queried_object_id() ) ) {
			return;
		}
		wp_enqueue_style(
			'ans-project-modules',
			plugins_url( 'assets/css/project-modules.css', ARS_NOVA_CORE_DIR . 'ars-nova-core.php' ),
			array(),
			ANSPM_VERSION
		);
	}
);
